#!/usr/bin/env python3
"""A small Jev experiment for classifying Markdown authorship signals."""

import argparse
import glob
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

API_URL = "https://api.typesafe.ai/v1/systemone"

QUESTIONS = {
    "authorship": {
        "type": "choice",
        "instructions": (
            "How likely is it that this text was primarily generated by an AI system? "
            "Human editing after generation still counts as AI-assisted. Use uncertain "
            "when the evidence is weak."
        ),
        "criteria": {
            "human": "Written primarily by a person without substantial AI generation",
            "ai_generated": "Written primarily by an AI system with little substantive human authorship",
            "uncertain": "There is not enough evidence to make a confident call",
        },
    },
    "human_authored": {
        "type": "noul",
        "instructions": "Was the underlying experience and main argument supplied by a human author?",
    },
    "ai_assistance": {
        "type": "noul",
        "instructions": "Does the text appear to have received meaningful assistance from an AI system?",
    },
    "fully_ai_generated": {
        "type": "noul",
        "instructions": "Was the text primarily generated by an AI system with little substantive human authorship?",
    },
    "personal_specificity": {
        "type": "score",
        "instructions": "How much concrete personal experience does the text contain?",
        "criteria": [
            "Generic or impersonal",
            "Some specific detail",
            "Strongly grounded in personal experience",
        ],
    },
    "formulaic_style": {
        "type": "noul",
        "instructions": "Does the text use strongly formulaic or templated language?",
    },
    "concrete_evidence": {
        "type": "noul",
        "instructions": "Does the text contain concrete events, measurements, tools, or observed results?",
    },
}


def body_only(text: str) -> str:
    return re.sub(r"\A---\n.*?\n---\n", "", text, count=1, flags=re.DOTALL).strip()


def request_jev(text: str, api_key: str) -> dict:
    payload = {"model": "jev-latest", "state": text, "questions": QUESTIONS}
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def simplify_result(result: dict) -> dict:
    answers = result["answers"]
    authorship = answers["authorship"]
    return {
        "label": authorship.get("choice"),
        "confidence": authorship.get("confidence"),
        "probabilities": authorship.get("probabilities"),
        "signals": {key: answers.get(key) for key in QUESTIONS if key != "authorship"},
        "model": result.get("model"),
    }


def read_text(path: str | None, state_mode: str = "full") -> str:
    if path:
        with open(path, encoding="utf-8") as file:
            text = file.read()
    elif not sys.stdin.isatty():
        text = sys.stdin.read()
    else:
        raise ValueError("Pass one or more text files, use --glob, or pipe text on stdin")
    return body_only(text) if state_mode == "body" else text


def expand_paths(paths: list[str], patterns: list[str]) -> list[str]:
    found = list(paths)
    for pattern in patterns:
        found.extend(glob.glob(pattern, recursive=True))
    unique = sorted({str(Path(path)) for path in found})
    if not unique:
        raise ValueError("No input files matched")
    return unique


def classify_file(path: str, api_key: str, state_mode: str) -> dict:
    text = read_text(path, state_mode)
    if not text.strip():
        raise ValueError(f"The input text is empty: {path}")
    result = simplify_result(request_jev(text, api_key))
    result["file"] = path
    result["state"] = state_mode
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Try Jev as a lightweight Markdown authorship classifier")
    parser.add_argument("files", nargs="*", help="text files to classify")
    parser.add_argument("--glob", action="append", default=[], help="glob pattern; may be repeated")
    parser.add_argument(
        "--state",
        choices=("full", "body"),
        default="full",
        help="send full input including frontmatter, or strip Astro frontmatter first",
    )
    args = parser.parse_args()

    try:
        api_key = os.environ.get("TYPESAFE_API_KEY")
        if not api_key:
            raise ValueError("Set TYPESAFE_API_KEY before making a Jev request")

        if args.files or args.glob:
            for path in expand_paths(args.files, args.glob):
                print(json.dumps(classify_file(path, api_key, args.state)))
        else:
            result = simplify_result(request_jev(read_text(None, args.state), api_key))
            result["state"] = args.state
            print(json.dumps(result, indent=2))
    except (OSError, ValueError, urllib.error.HTTPError, urllib.error.URLError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
