#!/usr/bin/env python3
"""A small Jev experiment for classifying Markdown authorship signals."""

import argparse
import glob
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

API_URL = "https://api.typesafe.ai/v1/systemone"

QUESTIONS = {
    "authorship": {
        "type": "choice",
        "instructions": (
            "Classify the text's authorship evidence, not whether it has polished grammar. "
            "Use human when a person appears to supply the experience and main argument; "
            "use ai_generated when an AI appears to supply most of the substantive text; "
            "use uncertain when the evidence is weak. Human editing after generation still "
            "counts as AI-assisted, and generic prose is not by itself evidence of AI generation."
        ),
        "criteria": {
            "human": "Written primarily by a person without substantial AI generation",
            "ai_generated": "Written primarily by an AI system with little substantive human authorship",
            "uncertain": "There is not enough evidence to make a confident call",
        },
    },
    "human_authored": {
        "type": "noul",
        "instructions": "Was the underlying experience and main argument supplied by a human author?",
    },
    "ai_assistance": {
        "type": "noul",
        "instructions": "Does the text appear to have received meaningful assistance from an AI system?",
    },
    "fully_ai_generated": {
        "type": "noul",
        "instructions": "Was the text primarily generated by an AI system with little substantive human authorship?",
    },
    "personal_specificity": {
        "type": "score",
        "instructions": "How much concrete personal experience does the text contain?",
        "criteria": [
            "Generic or impersonal",
            "Some specific detail",
            "Strongly grounded in personal experience",
        ],
    },
    "formulaic_style": {
        "type": "noul",
        "instructions": "Does the text use strongly formulaic or templated language?",
    },
    "concrete_evidence": {
        "type": "noul",
        "instructions": "Does the text contain concrete events, measurements, tools, or observed results?",
    },
}


def body_only(text: str) -> str:
    return re.sub(r"\A---\n.*?\n---\n", "", text, count=1, flags=re.DOTALL).strip()


def split_frontmatter(text: str) -> tuple[str, str]:
    match = re.match(r"\A---\n.*?\n---\n", text, flags=re.DOTALL)
    if not match:
        return "", text
    return match.group(0).strip(), text[match.end():]


def markdown_chunks(text: str, granularity: str, include_frontmatter: bool) -> list[dict]:
    frontmatter, body = split_frontmatter(text)
    lines = body.splitlines()
    sections = []
    current_heading = "Introduction"
    current_lines = []
    in_fence = False

    for line in lines:
        if line.strip().startswith("```"):
            in_fence = not in_fence
        heading = re.match(r"^(#{1,6})\s+(.+?)\s*$", line) if not in_fence else None
        if heading:
            sections.append((current_heading, "\n".join(current_lines).strip()))
            current_heading = heading.group(2)
            current_lines = []
        else:
            current_lines.append(line)
    sections.append((current_heading, "\n".join(current_lines).strip()))
    sections = [(heading, content) for heading, content in sections if content]

    chunks = []
    if granularity == "section":
        chunks = [{"section": heading, "paragraph_index": None, "text": content} for heading, content in sections]
    else:
        for heading, content in sections:
            paragraphs = [part.strip() for part in re.split(r"\n\s*\n", content) if part.strip()]
            for index, paragraph in enumerate(paragraphs, start=1):
                chunks.append({"section": heading, "paragraph_index": index, "text": paragraph})

    if include_frontmatter and frontmatter and chunks:
        chunks[0]["text"] = f"{frontmatter}\n\n{chunks[0]['text']}"
    return chunks


def request_jev(text: str, api_key: str) -> dict:
    payload = {"model": "jev-latest", "state": text, "questions": QUESTIONS}
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.load(response)
        except urllib.error.HTTPError as error:
            if error.code not in (429, 529) or attempt == 2:
                raise
            time.sleep(2**attempt)
    raise RuntimeError("Jev request failed after retries")


def simplify_result(result: dict) -> dict:
    answers = result["answers"]
    authorship = answers["authorship"]
    return {
        "label": authorship.get("choice"),
        "confidence": authorship.get("confidence"),
        "probabilities": authorship.get("probabilities"),
        "signals": {key: answers.get(key) for key in QUESTIONS if key != "authorship"},
        "model": result.get("model"),
    }


def signal_value(result: dict, name: str, field: str = "noul", default: float = 0.0) -> float:
    signal = result.get("signals", {}).get(name, {})
    value = signal.get(field, default)
    return value if isinstance(value, (int, float)) else default


def diagnose_result(result: dict) -> dict:
    """Turn Jev's raw signals into an editorial prompt, not a rewrite."""
    specificity = signal_value(result, "personal_specificity", "score")
    evidence = signal_value(result, "concrete_evidence")
    formulaic = signal_value(result, "formulaic_style")
    human_authored = signal_value(result, "human_authored")
    ai_assistance = signal_value(result, "ai_assistance")
    fully_ai = signal_value(result, "fully_ai_generated")

    if formulaic >= 0.7:
        category = "formulaic-language"
        question = "Which sentence is doing real work, and which wording is just a familiar template?"
    elif specificity < 0.75 and evidence < 0.45:
        category = "needs-concrete-evidence"
        question = "What did you actually observe, measure, decide or change here?"
    elif specificity < 0.75:
        category = "low-personal-specificity"
        question = "Which truthful first-hand detail would make this recognisably yours?"
    elif result.get("label") == "uncertain":
        category = "uncertain-review"
        question = "What is observation, what is interpretation, and what remains uncertain?"
    elif human_authored >= 0.65 and ai_assistance >= 0.6 and fully_ai < 0.45:
        category = "human-led-but-ai-assisted"
        question = "Does the wording still preserve your judgement and the specific experience behind it?"
    elif specificity >= 1.5 and evidence >= 0.6:
        category = "strong-grounded-writing"
        question = "Keep the concrete detail; remove only wording that does not add meaning."
    else:
        category = "review"
        question = "Can this claim be tied to something you personally saw, did or decided?"

    return {"category": category, "question": question}


def render_review_report(results: list[dict]) -> str:
    lines = [
        "# Jev editorial review",
        "",
        "This report is for improving truthful, specific writing. It is not a detector-evasion scorecard.",
        "",
    ]
    for number, result in enumerate(results, start=1):
        diagnosis = diagnose_result(result)
        paragraph = result.get("paragraph_index") or number
        specificity = signal_value(result, "personal_specificity", "score")
        evidence = signal_value(result, "concrete_evidence")
        formulaic = signal_value(result, "formulaic_style")
        text = result.get("text", "[text not included]").replace("\n", "\n> ")
        lines.extend([
            f"## Paragraph {paragraph} — {diagnosis['category']}",
            "",
            f"- File: `{result.get('file', 'stdin')}`",
            f"- Section: {result.get('section', 'n/a')}",
            f"- Jev label: `{result.get('label', 'n/a')}`",
            f"- Label confidence: `{result.get('confidence', 'n/a')}`",
            f"- Personal specificity: `{specificity}`",
            f"- Concrete evidence: `{evidence}`",
            f"- Formulaic style: `{formulaic}`",
            "",
            "> **Text**",
            "> " + text,
            "",
            f"**Editorial question:** {diagnosis['question']}",
            "",
        ])
    return "\n".join(lines)


def read_text(path: str | None, state_mode: str = "full") -> str:
    if path:
        with open(path, encoding="utf-8") as file:
            text = file.read()
    elif not sys.stdin.isatty():
        text = sys.stdin.read()
    else:
        raise ValueError("Pass one or more text files, use --glob, or pipe text on stdin")
    return body_only(text) if state_mode == "body" else text


def expand_paths(paths: list[str], patterns: list[str]) -> list[str]:
    found = list(paths)
    for pattern in patterns:
        found.extend(glob.glob(pattern, recursive=True))
    unique = sorted({str(Path(path)) for path in found})
    if not unique:
        raise ValueError("No input files matched")
    return unique


def classify(path: str | None, text: str, api_key: str, args: argparse.Namespace, metadata: dict) -> dict:
    if not text.strip():
        raise ValueError(f"The input text is empty: {path or 'stdin'}")
    result = simplify_result(request_jev(text, api_key))
    result.update(metadata)
    if path:
        result["file"] = path
    return result


def classify_file(path: str, api_key: str, args: argparse.Namespace) -> list[dict]:
    with open(path, encoding="utf-8") as file:
        original = file.read()
    text = body_only(original) if args.state == "body" else original
    if args.granularity == "file":
        return [classify(path, text, api_key, args, {"state": args.state, "granularity": "file"})]

    chunks = markdown_chunks(original if args.state == "full" else body_only(original), args.granularity, args.state == "full")
    results = []
    for index, chunk in enumerate(chunks, start=1):
        metadata = {
            "state": args.state,
            "granularity": args.granularity,
            "chunk_index": index,
            "chunk_count": len(chunks),
            "section": chunk["section"],
            "paragraph_index": chunk["paragraph_index"],
            "word_count": len(chunk["text"].split()),
        }
        if args.include_text or args.review_report:
            metadata["text"] = chunk["text"]
        results.append(classify(path, chunk["text"], api_key, args, metadata))
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description="Try Jev as a lightweight Markdown authorship classifier")
    parser.add_argument("files", nargs="*", help="text files to classify")
    parser.add_argument("--glob", action="append", default=[], help="glob pattern; may be repeated")
    parser.add_argument(
        "--state", choices=("full", "body"), default="full",
        help="send full input including frontmatter, or strip Astro frontmatter first",
    )
    parser.add_argument(
        "--granularity", choices=("file", "section", "paragraph"), default="file",
        help="judge the whole file, each Markdown section, or each paragraph",
    )
    parser.add_argument("--include-text", action="store_true", help="include chunk text in chunked output")
    parser.add_argument("--review-report", help="write an editorial Markdown review report")
    args = parser.parse_args()

    try:
        api_key = os.environ.get("TYPESAFE_API_KEY")
        if not api_key:
            raise ValueError("Set TYPESAFE_API_KEY before making a Jev request")

        results = []
        if args.files or args.glob:
            paths = expand_paths(args.files, args.glob)
            for path in paths:
                results.extend(classify_file(path, api_key, args))
        else:
            text = read_text(None, args.state)
            metadata = {"state": args.state, "granularity": "file"}
            if args.review_report:
                metadata["text"] = text
            results.append(classify(None, text, api_key, args, metadata))
        for result in results:
            if args.files or args.glob:
                print(json.dumps(result))
            else:
                print(json.dumps(result, indent=2))
        if args.review_report:
            with open(args.review_report, "w", encoding="utf-8") as report_file:
                report_file.write(render_review_report(results))
    except (OSError, ValueError, urllib.error.HTTPError, urllib.error.URLError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
