#!/usr/bin/env python3
"""A small Jev experiment for classifying Markdown authorship signals."""

import argparse
import glob
import json
import os

import sys
import urllib.error
import urllib.request
from pathlib import Path

API_URL = "https://api.typesafe.ai/v1/systemone"

QUESTIONS = {
    "authorship": {
        "type": "choice",
        "instructions": (
            "How likely is it that this text was primarily generated by an AI system? "
            "Use uncertain when the text may have been edited, is too short, or the evidence is weak."
        ),
        "criteria": {
            "human": "Written primarily by a person",
            "ai_generated": "Written primarily by an AI system",
            "uncertain": "There is not enough evidence to make a confident call",
        },
    },
    "personal_specificity": {
        "type": "score",
        "instructions": "How much concrete personal experience does the text contain?",
        "criteria": [
            "Generic or impersonal",
            "Some specific detail",
            "Strongly grounded in personal experience",
        ],
    },
    "formulaic_style": {
        "type": "noul",
        "instructions": "Does the text use strongly formulaic or templated language?",
    },
    "concrete_evidence": {
        "type": "noul",
        "instructions": "Does the text contain concrete events, measurements, tools, or observed results?",
    },
}


def request_jev(text: str, api_key: str) -> dict:
    payload = {
        "model": "jev-latest",
        "state": text,
        "questions": QUESTIONS,
    }
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def simplify_result(result: dict) -> dict:
    answers = result["answers"]
    authorship = answers["authorship"]
    return {
        "label": authorship.get("choice"),
        "confidence": authorship.get("confidence"),
        "probabilities": authorship.get("probabilities"),
        "signals": {
            "personal_specificity": answers.get("personal_specificity"),
            "formulaic_style": answers.get("formulaic_style"),
            "concrete_evidence": answers.get("concrete_evidence"),
        },
        "model": result.get("model"),
    }


def read_text(path: str | None) -> str:
    if path:
        with open(path, encoding="utf-8") as file:
            return file.read()
    if not sys.stdin.isatty():
        return sys.stdin.read()
    raise ValueError("Pass one or more text files, use --glob, or pipe text on stdin")


def expand_paths(paths: list[str], patterns: list[str]) -> list[str]:
    found = list(paths)
    for pattern in patterns:
        found.extend(glob.glob(pattern, recursive=True))
    unique = sorted({str(Path(path)) for path in found})
    if not unique:
        raise ValueError("No input files matched")
    return unique


def classify_file(path: str, api_key: str) -> dict:
    text = read_text(path)
    if not text:
        raise ValueError(f"The input text is empty: {path}")
    result = simplify_result(request_jev(text, api_key))
    result["file"] = path
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Try Jev as a lightweight Markdown authorship classifier")
    parser.add_argument("files", nargs="*", help="text files to classify")
    parser.add_argument("--glob", action="append", default=[], help="glob pattern; may be repeated")
    args = parser.parse_args()

    try:
        api_key = os.environ.get("TYPESAFE_API_KEY")
        if not api_key:
            raise ValueError("Set TYPESAFE_API_KEY before making a Jev request")

        if args.files or args.glob:
            paths = expand_paths(args.files, args.glob)
            for path in paths:
                print(json.dumps(classify_file(path, api_key)))
        else:
            result = simplify_result(request_jev(read_text(None), api_key))
            print(json.dumps(result, indent=2))
    except (OSError, ValueError, urllib.error.HTTPError, urllib.error.URLError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
